### ISSUE TITLE
DigiByte binaries should be removed for v8.22.0-rc1 and v8.22.0-rc2

### ISSUE THREAD

**Issue by saltedlolly** [DigiByte-Core/digibyte#162] opened 2024-01-28 23:11 UTC
Given that we are now aware that there is a serious bug in these release candidates, I propose that we remove the binaries from GitHub, if not also the source code. We now know that the forking issue noticed on testnet is caused by this coin maturity issue and that it affects both these releases. Hopefully we are close to being ready for an RC3 release but I think the other releases should be taken down immediately. We do not want more people running them as there are already quite a lot of these node already.

**Comment by ghost** [comment] 2024-01-28 23:26
I completely agree with you. On mainnet you will see at least 24 Digibyte 8 nodes. ( rc1 / rc2 )

**Comment by beggsdl** [comment] 2024-01-28 23:42
I also agree. Thanks for bringing this up Olly.

**Comment by gto90** [comment] 2024-01-29 15:40
First, thank you for your contributions to testing the latest release candidates.  We are where we are with the generous time that you have volunteered!

That said, I am not in support of taking down at least the RC2 release for the following reasons:

1) This release is marked as a test release and is linked to a GitHub discussion regarding the issues we found with the release.  As such, the release has been doing precisely what was intended: to inspire community testing.  We thank the community tremendously for that.

2) These versions are tagged in the repository, can be built from source by anyone, and run on mainnet.  This is an uncontrollable risk of doing open-source blockchain development in complete transparency.  We can not stop anyone from running any version of the code committed to this public repository.

3) On the home page for this repository, you will note that the current release version is v7.17.3.  At the top of the RC1 and RC2 release pages, which you can only get to if you navigate explicitly to the releases page, there is a clear note that these are test builds and should be used to assist in testing.  Again, we can not do anything to prevent people from running these on mainnet if they choose to do so.

4) There is nothing that we would be able to do to prevent someone from building and deploying the develop branch onto mainnet.  We have to trust that the vast majority of the network would be prudent and only run the release that is marked as "latest" on the repository home page rather than any non latest release branches.

I am happy to discuss further and would appreciate feedback from other core maintainers.

**Comment by saltedlolly** [comment] 2024-01-29 16:35
@gto90 You make good points. I was just thinking that if we removed the binaries from the releases it will add some friction to make it less likely people will run them. Not everybody running these is a developer. Obviously in theory anyone can compile the code themselves but not everyone knows how to do that. Adding friction can be helpful, particularly as there are quite a few 8.22.0-rc2 nodes out there already.

Perhaps we could simply add a warning message to the release notes for each to advise people not to run them, now that we know for sure that they have a problem? If we can get RC3 out soon it solves the problem, but for now it would be good to discourage people.

**Comment by beggsdl** [comment] 2024-01-29 16:36
Thanks for the comment @gto90.  I had thought about the fact that anyone could build and run any version.  I felt removing the binaries would at least stop anyone who does not know how to build the core wallet from spinning up a new 8.22.0-rc1 or rc2  node.  I understand and respect what you are saying.

**Comment by beggsdl** [comment] 2024-01-29 16:41
One question I have is, what will happen on mainnet if someone running an 8.22.0-rc1 or rc2 node prematurely spends a coinbase tx?  It will be a valid transaction for the 8.22 nodes, but not the 7.17.x nodes.  Will the 8.22 nodes end up forking on to their own chain?  Since we have so many 7.17.x nodes on mainnet (unlike what we had on testnet), will the 7.17.x chain win and the 8.22 nodes abandon that "bad" tx and get back on the 7.17.x chain?  Would the 7.17.x nodes choke on that "bad" tx and stop processing new blocks?  I am just having trouble figuring out what the impact could be and what could happen.

**Comment by Sbosvk** [comment] 2024-01-29 17:06
I don't personally care one way or the other about the binaries, but I strongly oppose removing any version of any source code. For an outside observer this will only raise suspicion, and keeping the code may be helpful in avoiding similar caveats in the future.

**Comment by saltedlolly** [comment] 2024-01-29 17:37
@Sbosvk I think I worded it poorly because that wasn't really I meant. We obviously don't want to lose the record of the releases entirely, but it is important to discourage people from running rc2. It caused a massive problem on testnet which fortunately doesn't have a financial cost. On mainnet it could cause real harm...

**Comment by saltedlolly** [comment] 2024-01-29 17:52
@beggsdl I think we would see exactly what happened on testnet - transactions made from nodes that are mining could fork the chain if they try and send a transaction containing a coinbase transaction that is not matured. Once forked they would remain stuck on their respective chain. In short, it would be bad!

**Comment by JaredTate** [comment] 2024-01-29 22:03
We are very close to an RC3. I would feel comfortable with an RC3 version as soon as we double-check the previous dandelion and mempool issues we had. I will test those this week. In mean meantime, I see no reason that we could not cut an RC2.1 today/tomorrow with the maturity fixes, as soon as that PR is approved. Would be great to test mine those. I could cut/ compile the binary releases for a 2.1 today/ tomorrow if everyone thinks that's a good idea. 

I definitely agree the less nodes running RC1 & RC2 the better. So the quicker we give another option the better. It might take another month for an RC3 though, just being realistic.

Or maybe we should call it RC3 and then do RC4... doesn't matter to me, we could call it RC2.1 or RC2.5 or just 3.

**Comment by saltedlolly** [comment] 2024-01-29 22:15
It seems unnecessary to cut an RC2.1 even if the other one is a month away. That is just creating extra work for little gain. Better to push hard on getting RC3 ready. We could just add a warning message to the RC2 release notes for the next few weeks weeks in my opinion. Deleting the RC2 binaries from the release would be even better. Till then everyone should still run 7.17.3 or they can compile the latest develop branch and help test.

**Comment by saltedlolly** [comment] 2024-01-29 22:18
However if we discover another showstopper then perhaps we should reconsider!

**Comment by ycagel** [comment] 2024-02-04 01:42
The appropriate warning messages were placed in RC2 & RC3 release notes to inform everyone.

**Closed as completed** 2024-02-04 01:42 UTC
