### ISSUE TITLE
Encrypted Wallet Freezes Frequently (RPC Locking Bug)

### ISSUE THREAD

**Issue by areebmajeed** [DigiByte-Core/digibyte#100] opened 2022-09-27 01:27 UTC
This issue affected Bitcoin, Bitcoin Cash, and other coins.

Please refer to the following discussions:

https://github.com/bitcoin/bitcoin/pull/18487
https://gitlab.com/bitcoin-cash-node/bitcoin-cash-node/-/issues/327

**Comment by ghost** [comment] 2024-02-04 20:11
Lets close this pr? Link to another site. And it is not about DigiByte core. :/

**Comment by beggsdl** [comment] 2024-02-04 20:42
I have my wallet that is receiving all my testnet mining rewards encrypted. So it is receiving many transactions. I have also sent a number of transactions. I’m not seen any issues. The wallet is a little laggy sometimes, but I wonder if that is due to the large volume of txs in the wallet. It has not frozen at all.

**Comment by Sbosvk** [comment] 2024-02-04 20:53
Reading through the conversation on the linked issue it looks like (if I understand it correctly) this issue has been fixed in upstream BTC core, and also the issue seemed to be caused by several factors, including very specific and non-best approach calls.

**Comment by ycagel** [comment] 2024-02-05 00:20
Appreciate the feedback from everyone. I am closing the issue.

**Closed as completed by ycagel** 2024-02-05 00:20 UTC
