### ISSUE TITLE
Imported a private key, the balance shows correct but can't send funds

### ISSUE THREAD

**Issue by skironDotNet** [DigiByte-Core/digibyte#202] opened 2024-03-15 21:28 UTC
Digibyte-qt v7.17.3 for Linux
After importing a private key with confirmed balance, the balance is shown but coin control window shows no inputs.
When trying to send, the wallets displays "The amount exceeds your balance." when clicked "Use available balance" it turns entry field to 0.

The chain is synced. In debug console list-unspent shows nothing.

Can this be related to the fact now HD wallet is forced in this version to must be enabled and the coin control or otherwise UTXO check doesn't include imported keys?

**Comment by ghost** [comment] 2024-03-15 21:34
https://github.com/DigiByte-Core/digibyte/pull/182 this pr should fix it.

**Comment by skironDotNet** [comment] 2024-03-15 21:35
in which version this fix to be expected? I'm hesitant to run 8.x.x-RC

**Comment by skironDotNet** [comment] 2024-03-15 21:50
actually I looked at the commit, looks like an easy fix, I'll just for from 7.17.3 and build my own with this fix. Thank you

**Comment by ghost** [comment] 2024-03-15 21:52
This fix is in RC4.

**Comment by ycagel** [comment] 2024-03-15 21:54
Are we able to close this issue?

**Comment by skironDotNet** [comment] 2024-03-15 21:58
yes

**Comment by skironDotNet** [comment] 2024-03-15 22:12
Should not have closed that, the 7.17.3 does not even have a variable `DEFAULT_MAX_DEPTH`
How the bug preventing spending is present in a version released in Jun 21, 2020, that's like almost 4 years when people can't spend

**Comment by skironDotNet** [comment] 2024-03-15 22:14
@Jongjan88 there is no RC4 as well... no wonder DGB has hard time to grow in price if things are broken for so long (sorry to say)

**Comment by ghost** [comment] 2024-03-15 22:38
@skironDotNet it only affects old wallets. Coins in blocks older then 9999999999 so the problem is not that old. but will be fixed in rc4. You can build DigiByte 8 dev branch.

**Comment by skironDotNet** [comment] 2024-03-15 22:40
So the Dev is stable enough to just send funds? Many thanks

**Comment by ghost** [comment] 2024-03-15 22:43
It is rc3 with some small changes. Make first good backups off your private key. And first test small amount.

**Comment by skironDotNet** [comment] 2024-03-17 04:12
I just complied develop and tested, and it works. I would not close the issue until RC4 is released. But feel free to close, since this is technically fixed via #182

**Closed as completed** 2024-03-17 06:09 UTC
