### ISSUE TITLE
Netflix Bug

### ISSUE THREAD

**Issue by mctrivia** [DigiByte-Core/digibyte#181] opened 2024-02-29 22:50 UTC
Really old wallets can not spend all there DigiByte.  This has been commonly refereed to as the netflix bug because the fix proposed by Jered was to delete the block history and while the wallet was syncing continuously try sending the funds to a new address which takes hours.

I think I may know what causes this bug.  The listunspent commands default max confirms is 9,999,999 which is only half the age of DigiByte.  I believe the bug is a result of the standard send command using the default value which in really old wallets will not find all utxos.

Even if this is not the cause of the bug this default value should be increased to the max integer value or at least add 1 more 9 to the number so it is longer then the chain.

**Comment by Sbosvk** [comment] 2024-02-29 22:55
Thanks for creating this issue. It would be fantastic if it turns out  the root cause of this bug was finally identified as it affects long-term holders.

**Comment by mctrivia** [comment] 2024-03-01 02:53
Well it has now been confirmed this is the cause of the bug.

**Comment by ycagel** [comment] 2024-03-01 14:01
@mctrivia Do you have a PR to fix this issue?

**Comment by mctrivia** [comment] 2024-03-01 14:11
https://github.com/DigiByte-Core/digibyte/pull/182

**Comment by ycagel** [comment] 2024-03-05 16:30
https://github.com/DigiByte-Core/digibyte/pull/182 was merged.

**Closed as completed by ycagel** 2024-03-05 16:30 UTC
