### ISSUE TITLE
Bug: Testnet received transactions 'from' value says 'unknown'

### ISSUE THREAD

**Issue by saltedlolly** [DigiByte-Core/digibyte#153] opened 2023-12-26 17:47 UTC
Spotted by @JongJan88. In the fast start code 8.22.0 fast start code, after sending a transaction, the 'from' value says 'unknown':

![IMG_0827](https://github.com/DigiByte-Core/digibyte/assets/642592/bb9914d6-9cc8-4e32-ab87-0b211f1081a1)

**Comment by beggsdl** [comment] 2024-01-05 02:09
@Jongjan88 - Do you know if this tx was on the long chain during the fork?

I was looking in the block explorer and this TX ID does not exist.  And there is a gap in transactions for that address from 20-Dec to 31-Dec.
![image](https://github.com/DigiByte-Core/digibyte/assets/35427422/72d375ca-a3ab-4544-b410-00454f88be37)

And in the code, it looks like "From: unknown" should appear when it is an offline transaction.  Someone please correct me if I am wrong about that.

**Comment by ghost** [comment] 2024-01-06 15:32
> Do you know if this tx was on the long chain during the fork?
> I was looking in the block explorer and this TX ID does not exist. And there is a gap in transactions for that address from 20-Dec to 31-Dec.

No, sorry, I switched back and forth during that time. from the short to the long chain.

> And in the code, it looks like "From: unknown" should appear when it is an offline transaction. Someone please correct me if I am wrong about that.

Yes looks like **wtx.value_map["from"]** is empty.

**Comment by beggsdl** [comment] 2024-01-29 17:32
I just saw this same "From: unknown" issue in a transaction sent from a 7.17.3 wallet to an 8.22.0.rcx wallet.
![image](https://github.com/DigiByte-Core/digibyte/assets/35427422/6d27054c-f426-4e1f-a04a-d7e615f87837)

**Comment by ghost** [comment] 2024-02-03 02:22
I install dgb7 and Bitcoin 26 to test this PR. And when i receive a transaction. it also say **unknown**
So i think we can close this PR.

![Screenshot from 2024-02-03 03-17-30](https://github.com/DigiByte-Core/digibyte/assets/125610144/3144c147-f806-48ad-b2e4-5a161e5c208d)

**Comment by ycagel** [comment] 2024-02-04 18:15
@JaredTate What do you think about closing this issue?

**Comment by ycagel** [comment] 2024-02-06 16:38
Based on the feedback from the other reviewers, the unknown field is showing up in older versions of Bitcoin and DigiByte wallets. The issue is being closed.

**Closed as completed by ycagel** 2024-02-06 16:38 UTC
